name: KCC Cloud Run Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  GCP_PROJECT_ID: ais-europe-west2-116319078cfc4
  GCP_REGION: europe-west2
  CLOUD_RUN_SERVICE: kitora-command-center
